### ISSUE TITLE
Some chords get changed on /files/slide.html

### ISSUE THREAD

**Issue by secorrales** [tomasss1024/openlp_chords#1]
Noticed that some chords, even though they are correct when input, will get changed. [so far I've seen it with Bm. It will get translated to A#m].

Other minor chords seem to display properly [I.e. -Dm, Am].

I take a look at the JS un the file soon to see if I can figure out why it's happening with some chords.

![bug1](https://cloud.githubusercontent.com/assets/12451401/23834362/53a8b6ee-0723-11e7-9533-3ce7647fa6f6.PNG)
![bug2](https://cloud.githubusercontent.com/assets/12451401/23834366/5f20e2bc-0723-11e7-841c-5c99ec894ae8.PNG)

**Comment by tomasss1024** [comment]
You can change your preferred notes in chords.js (or slide.js) as you need:
`notesPreferred = ['b','#','#','#','#','#','#','#','#','#','#','#'];`
to
`notesPreferred = ['b','#','#','#','#','#','#','#','#','#','b','#'];`

**Comment by secorrales** [comment]
Thank you so much for the reply!

**Comment by secorrales** [comment]
@tomasss1024 ,
I'm still seeing the issue in "slash" chords.  For example, chord G/B will display as G/A#
The change you suggested works great for regular chords.  Am I missing something?
Thanks for your help!
